from __future__ import annotations

import json
from typing import Any, Dict, List, Optional
from sitedna.spec.schema import SiteDNA, EntryAnimation, ScrollAnimation, MouseParallaxLayer


def easing_to_framer(easing: List[float]) -> str:
    if len(easing) == 4:
        return f"[{', '.join(str(v) for v in easing)}]"
    return '"easeOut"'


def generate_mouse_parallax_hook() -> str:
    return '''// hooks/useMouseParallax.ts — generated by SiteDNA codegen
import { useEffect, useRef } from "react";

interface MouseParallaxOptions {
  strength?: number;
  invert?: boolean;
  ease?: number;
  restingScale?: number;
}

export function useMouseParallax(options: MouseParallaxOptions = {}) {
  const { strength = 15, invert = false, ease = 0.08, restingScale = 1.05 } = options;
  const ref = useRef<HTMLElement | null>(null);
  const current = useRef({ x: 0, y: 0 });
  const target = useRef({ x: 0, y: 0 });
  const rafId = useRef<number>(0);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleMouseMove = (e: MouseEvent) => {
      const rect = document.documentElement.getBoundingClientRect();
      const cx = e.clientX - rect.width / 2;
      const cy = e.clientY - rect.height / 2;
      const nx = cx / (rect.width / 2);
      const ny = cy / (rect.height / 2);
      target.current.x = nx * strength * (invert ? -1 : 1);
      target.current.y = ny * strength * (invert ? -1 : 1);
    };

    const tick = () => {
      current.current.x += (target.current.x - current.current.x) * ease;
      current.current.y += (target.current.y - current.current.y) * ease;
      if (el) {
        el.style.transform = `scale(${restingScale}) translate3d(${current.current.x}px, ${current.current.y}px, 0)`;
      }
      rafId.current = requestAnimationFrame(tick);
    };

    window.addEventListener("mousemove", handleMouseMove, { passive: true });
    rafId.current = requestAnimationFrame(tick);

    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
      cancelAnimationFrame(rafId.current);
    };
  }, [strength, invert, ease, restingScale]);

  return ref;
}
'''


def generate_motion_variants(spec: SiteDNA) -> str:
    variants: Dict[str, Any] = {}

    for anim in spec.motion.entry:
        target_key = anim.target.replace(".", "_").replace("-", "_")
        easing = easing_to_framer(anim.easing)
        variant_props_initial: Dict[str, Any] = {}
        variant_props_animate: Dict[str, Any] = {}

        props = anim.props
        if isinstance(props, dict):
            for prop, values in props.items():
                if isinstance(values, list) and len(values) == 2:
                    variant_props_initial[prop] = values[0]
                    variant_props_animate[prop] = values[1]

        variants[target_key] = {
            "hidden": variant_props_initial,
            "visible": {
                **variant_props_animate,
                "transition": {
                    "duration": anim.duration,
                    "delay": anim.delay,
                    "ease": easing,
                },
            },
        }

    if variants:
        variants_json = json.dumps(variants, indent=2)
        return f"""// motion/variants.ts — generated by SiteDNA codegen
export const siteVariants = {variants_json} as const;

export const staggerContainer = {{
  hidden: {{}},
  visible: {{
    transition: {{
      staggerChildren: 0.08,
    }},
  }},
}};

export const clipReveal = {{
  hidden: {{ y: '100%' }},
  visible: {{
    y: '0%',
    transition: {{ duration: 0.7, ease: [0.25, 0.1, 0.25, 1] }},
  }},
}};
"""
    return """// motion/variants.ts — no entry animations detected
export const siteVariants = {};
export const staggerContainer = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};
"""


def generate_scroll_hooks(spec: SiteDNA) -> str:
    if not spec.motion.scroll_linked:
        return """// motion/useScrollAnimations.ts — no scroll animations detected
export function useScrollAnimations() {
  return {};
}
"""

    hook_bodies = []
    for i, anim in enumerate(spec.motion.scroll_linked[:6]):
        target = anim.target.replace(".", "_").replace("-", "_")
        if anim.formula:
            coeff_match = __import__("re").search(r"scrollY\s*\*\s*(-?\d+\.?\d*)", anim.formula)
            coeff = float(coeff_match.group(1)) if coeff_match else -0.05
        else:
            coeff = -0.05

        hook_bodies.append(
            f"  const {target}_y = useTransform(scrollY, [0, 3000], [0, {int(3000 * coeff)}]);"
        )

    hooks_str = "\n".join(hook_bodies)
    returns = ", ".join(
        anim.target.replace(".", "_").replace("-", "_") + "_y"
        for anim in spec.motion.scroll_linked[:6]
    )

    return f"""// motion/useScrollAnimations.ts — generated by SiteDNA codegen
import {{ useScroll, useTransform }} from 'framer-motion';

export function useScrollAnimations() {{
  const {{ scrollY }} = useScroll();
{hooks_str}
  return {{ {returns} }};
}}
"""
