from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, Optional

from sitedna.spec.schema import SiteDNA
from sitedna.codegen.tokens import generate_tailwind_config, generate_css_variables, generate_font_faces
from sitedna.codegen.layout import generate_app_component, generate_section_component, generate_grid_overlap_wrapper
from sitedna.codegen.motion import generate_motion_variants, generate_scroll_hooks, generate_mouse_parallax_hook


VITE_PACKAGE_JSON = """{
  "name": "cloneforge-output",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "framer-motion": "^11.0.0",
    "lenis": "^1.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.0.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.0",
    "tailwindcss": "^3.4.0",
    "typescript": "^5.2.0",
    "vite": "^5.0.0"
  }
}"""

VITE_CONFIG = """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: { port: 3000 },
});
"""

TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"]
}
"""

INDEX_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
    {font_face}
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>"""

MAIN_TSX = """import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
"""

LENIS_README = """# CloneForge React Scaffold

This project was generated by **CloneForge** from a SiteDNA capture.

## Quick Start

```bash
npm install
npm run dev
```

## Structure

```
src/
  App.tsx             — Root layout
  index.css           — CSS variables + global styles
  components/         — Per-section components
  motion/             — Framer Motion variants + scroll hooks
  hooks/              — Custom hooks (useMouseParallax, etc.)
public/
  assets/             — Place harvested images here
```

## What to do next

1. Place your harvested images in `public/assets/`
2. Install fonts: check `index.css` for the Google Fonts import
3. Run `npm run dev` and iterate on the components
4. Use GlassBench visual diff to measure fidelity
"""


class ScaffoldGenerator:
    def __init__(self, spec: SiteDNA, output_dir: str) -> None:
        self.spec = spec
        self.out = Path(output_dir)

    def generate(self) -> Dict[str, int]:
        files_written: Dict[str, int] = {}
        self.out.mkdir(parents=True, exist_ok=True)

        self._write("package.json", VITE_PACKAGE_JSON)
        self._write("vite.config.ts", VITE_CONFIG)
        self._write("tsconfig.json", TSCONFIG)
        self._write("README.md", LENIS_README)
        files_written["config"] = 4

        font_tag = '<link rel="preconnect" href="https://fonts.googleapis.com">'
        title = self.spec.source.url.split("/")[2] if "//" in self.spec.source.url else "CloneForge Output"
        self._write("index.html", INDEX_HTML_TEMPLATE.format(title=title, font_face=font_tag))
        files_written["index.html"] = 1

        src = self.out / "src"
        src.mkdir(exist_ok=True)

        self._write("src/main.tsx", MAIN_TSX)
        self._write("src/App.tsx", generate_app_component(self.spec))
        self._write("src/index.css", self._build_index_css())
        files_written["src/core"] = 3

        tailwind_cfg = generate_tailwind_config(self.spec)
        self._write("tailwind.config.js", tailwind_cfg)
        files_written["tailwind"] = 1

        components_dir = src / "components"
        components_dir.mkdir(exist_ok=True)
        for i, section in enumerate(self.spec.layout.sections):
            filename = f"src/components/{self._component_name(section.id)}.tsx"
            self._write(filename, generate_section_component(section, i))
        files_written["components"] = len(self.spec.layout.sections)

        motion_dir = src / "motion"
        motion_dir.mkdir(exist_ok=True)
        self._write("src/motion/variants.ts", generate_motion_variants(self.spec))
        self._write("src/motion/useScrollAnimations.ts", generate_scroll_hooks(self.spec))
        files_written["motion"] = 2

        hooks_dir = src / "hooks"
        hooks_dir.mkdir(exist_ok=True)
        self._write("src/hooks/useMouseParallax.ts", generate_mouse_parallax_hook())
        files_written["hooks"] = 1

        public = self.out / "public"
        (public / "assets").mkdir(parents=True, exist_ok=True)
        asset_manifest = [
            {
                "id": a.id,
                "kind": a.kind,
                "url": a.url,
                "alpha": a.alpha,
                "dimensions": a.dimensions,
                "generation_prompt": a.generation_prompt,
            }
            for a in self.spec.assets
        ]
        self._write("public/assets/manifest.json", json.dumps(asset_manifest, indent=2))
        files_written["assets"] = 1

        self._write("sitedna.json", json.loads(self.spec.model_dump_json()))
        files_written["spec"] = 1

        return files_written

    def _build_index_css(self) -> str:
        parts = [
            generate_font_faces(self.spec),
            "",
            generate_css_variables(self.spec),
            "",
            """*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html { scroll-behavior: auto; }
body { font-family: var(--font-display, 'EB Garamond', serif); }
""",
        ]
        return "\n".join(parts)

    def _component_name(self, sec_id: str) -> str:
        words = sec_id.replace("-", "_").replace(".", "_").split("_")
        return "".join(w.capitalize() for w in words) + "Section"

    def _write(self, relative_path: str, content: Any) -> None:
        target = self.out / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        mode = "w"
        if isinstance(content, dict) or isinstance(content, list):
            content = json.dumps(content, indent=2)
        with open(target, mode, encoding="utf-8") as f:
            f.write(content)
