from __future__ import annotations

from typing import Any, Dict, List, Optional
from sitedna.spec.schema import SiteDNA, ColorToken, TypeFace


def generate_tailwind_config(spec: SiteDNA) -> str:
    palette_vars = {}
    for token in spec.tokens.palette:
        key = token.role.replace(".", "-")
        palette_vars[key] = token.hex

    display_font = spec.tokens.type.display
    display_stack = display_font.stack if display_font else ["EB Garamond", "serif"]
    body_font = spec.tokens.type.body
    body_stack = body_font.stack if body_font else ["Inter", "sans-serif"]
    font_family_str = ", ".join(f'"{f}"' if " " in f else f for f in display_stack)
    body_family_str = ", ".join(f'"{f}"' if " " in f else f for f in body_stack)

    spacing_rhythm = spec.tokens.spacing.get("rhythm", [8, 16, 24, 40, 64, 96])
    spacing_entries = "\n".join(
        f"      '{i}': '{v}px'," for i, v in enumerate(spacing_rhythm)
    )

    colors_entries = "\n".join(
        f"      '{k}': '{v}'," for k, v in palette_vars.items()
    )

    return f"""// tailwind.config.js — generated by SiteDNA codegen
/** @type {{import('tailwindcss').Config}} */
export default {{
  content: ['./index.html', './src/**/*.{{js,ts,jsx,tsx}}'],
  theme: {{
    extend: {{
      colors: {{
{colors_entries}
      }},
      fontFamily: {{
        display: [{font_family_str}],
        body: [{body_family_str}],
        mono: ['JetBrains Mono', 'monospace'],
      }},
      spacing: {{
{spacing_entries}
      }},
    }},
  }},
  plugins: [],
}};
"""


def generate_css_variables(spec: SiteDNA) -> str:
    lines = [":root {"]

    for token in spec.tokens.palette:
        var_name = "--color-" + token.role.replace(".", "-")
        lines.append(f"  {var_name}: {token.hex};")

    display_font = spec.tokens.type.display
    if display_font and display_font.scale:
        scale = display_font.scale[0]
        lines.append(f"  --font-size-display: {scale.size};")
        if scale.tracking:
            lines.append(f"  --letter-spacing-display: {scale.tracking};")
        if scale.leading:
            lines.append(f"  --line-height-display: {scale.leading};")

    easing = spec.tokens.easing
    if easing.standard:
        vals = ", ".join(str(v) for v in easing.standard)
        lines.append(f"  --ease-standard: cubic-bezier({vals});")
    if easing.expressive:
        vals = ", ".join(str(v) for v in easing.expressive)
        lines.append(f"  --ease-expressive: cubic-bezier({vals});")

    radii = spec.tokens.radii
    for i, r in enumerate(radii[:4]):
        lines.append(f"  --radius-{i}: {r}px;")

    lines.append("}")
    return "\n".join(lines)


def generate_font_faces(spec: SiteDNA) -> str:
    display_font = spec.tokens.type.display
    if not display_font:
        return ""

    matched_family = "EB Garamond"
    if display_font.matched:
        matched_family = display_font.matched.get("family", "EB Garamond")

    safe_name = matched_family.replace(" ", "")

    return f"""/* Font faces — generated by SiteDNA codegen */

/* Option A: Load from Google Fonts at runtime */
@import url('https://fonts.googleapis.com/css2?family={matched_family.replace(" ", "+")}:ital,wght@0,400;0,600;1,400&display=swap');

/* Option B: Self-hosted (place font files in /public/fonts/) */
/* @font-face {{
  font-family: '{matched_family}';
  src: url('/fonts/{safe_name}-Regular.woff2') format('woff2'),
       url('/fonts/{safe_name}-Regular.woff') format('woff');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}}

@font-face {{
  font-family: '{matched_family}';
  src: url('/fonts/{safe_name}-Italic.woff2') format('woff2');
  font-weight: 400;
  font-style: italic;
  font-display: swap;
}} */
"""
